# Generated by Django 4.2.5 on 2023-12-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
    ]
