# Generated by Django 4.2.5 on 2023-12-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231223_1946'),
    ]

    operations = [
    ]
